// Generated by CoffeeScript 1.10.0
(function() {
  var Base, Slack, nodeSlack;

  Base = require('mocha').reporters.base;

  nodeSlack = require('node-slack');

  Slack = (function() {
    function Slack(runner, options) {
      var failures, passes, slack;
      passes = 0;
      failures = 0;
      slack = new nodeSlack(options.reporterOptions.hook_url);
      if (!options.reporterOptions.minimal && !options.reporterOptions.failureOnly) {
        runner.on("pass", function(test) {
          var messageOptions;
          passes++;
          messageOptions = {
            username: "PASS: " + test.fullTitle(),
            text: test.fullTitle(),
            channel: options.reporterOptions.channel
          };
          if (options.reporterOptions.passIcon) {
            messageOptions.icon_emoji = options.reporterOptions.passIcon;
          }
          slack.send(messageOptions);
        });
      }
      runner.on("fail", function(test, err) {
        var messageOptions;
        failures++;
        messageOptions = {
          username: "FAIL: " + test.fullTitle(),
          text: err.message,
          channel: options.reporterOptions.channel
        };
        if (options.reporterOptions.failicon) {
          messageOptions.icon_emoji = options.reporterOptions.failicon;
        }
        slack.send(messageOptions);
      });
      if (!options.reporterOptions.failureOnly) {
        runner.on("end", function() {
          var messageOptions;
          messageOptions = {
            username: " Tests Completed",
            text: "Passed: " + passes + " Failed: " + failures,
            channel: options.reporterOptions.channel
          };
          if (options.reporterOptions.endIcon) {
            messageOptions.icon_emoji = options.reporterOptions.endIcon;
          }
          slack.send(messageOptions);
        });
      }
    }

    return Slack;

  })();

  module.exports = Slack;

}).call(this);
